import React, { useEffect, useState } from 'react';
import { InvoiceRow, AuditSummary } from '../types';
import { geminiService } from '../geminiService';
import { FileDown, Loader2, FileText } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface ReportViewProps {
  data: InvoiceRow[];
  summary: AuditSummary;
}

const ReportView: React.FC<ReportViewProps> = ({ data, summary }) => {
  const [reportMarkdown, setReportMarkdown] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const generate = async () => {
      const result = await geminiService.generateReport(data, summary);
      setReportMarkdown(result);
      setLoading(false);
    };
    generate();
  }, [data, summary]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="p-8 max-w-5xl mx-auto h-full overflow-y-auto">
      <div className="flex justify-between items-center mb-8 print:hidden">
        <div>
           <h2 className="text-2xl font-bold text-slate-900">Audit Report Generation</h2>
           <p className="text-slate-500">Draft Internal Audit Memorandum</p>
        </div>
        <button
          onClick={handlePrint}
          disabled={loading}
          className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-lg hover:bg-slate-800 transition-all shadow-lg"
        >
          <FileDown className="w-5 h-5" />
          Export to PDF
        </button>
      </div>

      {loading ? (
        <div className="h-96 flex flex-col items-center justify-center space-y-4">
          <Loader2 className="w-10 h-10 animate-spin text-blue-600" />
          <p className="text-slate-500 animate-pulse">Generating substantive audit report...</p>
        </div>
      ) : (
        <div className="bg-white p-12 rounded-xl shadow-sm border border-slate-200 min-h-[800px] print:shadow-none print:border-none">
          <div className="flex items-center gap-3 mb-8 border-b border-slate-100 pb-6">
             <div className="w-12 h-12 bg-slate-900 rounded-lg flex items-center justify-center">
                <FileText className="text-white w-6 h-6" />
             </div>
             <div>
               <h1 className="text-3xl font-serif text-slate-900">Audit Memorandum</h1>
               <p className="text-slate-500 text-sm mt-1">Ref: AR-2023-AUDIT-GUARD</p>
             </div>
          </div>
          
          <div className="prose prose-slate prose-headings:font-serif prose-headings:font-bold prose-h1:text-2xl prose-h2:text-xl prose-a:text-blue-600 max-w-none">
             <ReactMarkdown>{reportMarkdown}</ReactMarkdown>
          </div>

          <div className="mt-16 pt-8 border-t border-slate-200 flex justify-between text-xs text-slate-400 font-mono">
            <span>Generated by AuditGuard AI</span>
            <span>{new Date().toLocaleDateString()}</span>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportView;
